apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: mbissouri
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017
        resources:
          requests:
            cpu: "300m"
            memory: "300Mi"
          limits:
            cpu: "400m"
            memory: "400Mi"
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: "root"
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: "root"
      livenessProbe:
        tcpSocket:
          port: 27017
        initialDelaySeconds: 30
        periodSeconds: 10
        failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: mbissouri
spec:
  selector:
    app: mongodb
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
  type: ClusterIP