apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdb
  namespace: mbissouri
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webdb
  template:
    metadata:
      labels:
        app: webdb
    spec:
      containers:
      - name: webdb
        image: melbissouri/webdb
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://root:root@mongodb-service.mbissouri.svc.cluster.local:27017/"
        - name: MONGO_DB_NAME
          value: "flask_app_db"
        - name: MONGO_COLLECTION_NAME
          value: "requests"
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "200m"
            memory: "200Mi"
        livenessProbe:
          httpGet:
            path: /jj
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 5
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: webdb-service
  namespace: mbissouri
spec:
  selector:
    app: webdb
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP