version: '3.8'

services:
  flask:
    build:
      context: .  
    container_name: flask-app
    ports:
      - "5000:5000"  
    depends_on:
      - mongodb  
    environment:
      - MONGO_USERNAME=${MONGO_USERNAME} 
      - MONGO_PASSWORD=${MONGO_PASSWORD}  
      - MONGO_HOST=${MONGO_HOST} 

    networks:
      - flask-mongo-network

  mongodb:
    image: mongo:latest  
    container_name: mongodb
    ports:
      - "27017:27017"  
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}  
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}  
    networks:
      - flask-mongo-network

networks:
  flask-mongo-network:
