version: '3.8'

services:
  flask-app-db:
    build:
      context: .
    container_name: flask-app-db
    environment:
      - FLASK_ENV=development
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=password
      - MONGO_HOST=mongodb
    ports:
      - "5001:5000"  # Flask App connected to MongoDB
    depends_on:
      - mongodb
    networks:
      - flask-network

  flask-app-simple:
    build:
      context: .
    container_name: flask-app-simple
    command: ["python", "app_simple.py"]
    environment:
      - FLASK_ENV=development
    ports:
      - "5002:5000"  # Flask App without MongoDB
    networks:
      - flask-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"  # MongoDB
    volumes:
      - mongo-data:/data/db
    networks:
      - flask-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"  # NGINX as Load Balancer
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"  # NGINX config
    depends_on:
      - flask-app-db
      - flask-app-simple
    networks:
      - flask-network

volumes:
  mongo-data:

networks:
  flask-network:
