apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdb
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: webdb
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1    
  template:
    metadata:
      labels:
        app: webdb
    spec:
      containers:
      - name: webdb
        image: {{ .Values.image.webdb }}
        ports:
        - containerPort: {{ .Values.ports.webdb }}
        env:
        - name: MONGO_URL
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: DB_HOST
        - name: MONGO_DB_NAME
          value: "{{ .Values.mongodb.dbName }}"
        - name: MONGO_COLLECTION_NAME
          value: "{{ .Values.mongodb.collectionName }}"
        resources:
          requests: {{ .Values.resources.requests | toYaml | nindent 12 }}
          limits: {{ .Values.resources.limits | toYaml | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: webdb-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: webdb
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.ports.webdb }}
  type: ClusterIP
