apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
  namespace: mbissouri
data:
  DB_HOST: mongodb-0.mongodb.mbissouri.svc.cluster.local
  DB_PORT: "27017"
  DB_USER: admin
  DB_PASSWORD: admin
  init-replica-set.sh: |
    #!/bin/bash
    echo "Waiting for MongoDB to start..."
    sleep 10
    echo "Initiating replica set..."
    mongo --host localhost:27017 <<EOF
      rs.initiate({
        _id: "{{ .Values.mongodb.replicaSetName }}",
        members: [
          { _id: 0, host: "mongodb-0.mongodb:27017" },
          { _id: 1, host: "mongodb-1.mongodb:27017" },
          { _id: 2, host: "mongodb-2.mongodb:27017" }
        ]
      })
    EOF
    echo "Replica set initialized."
