apiVersion: apps/v1
kind: Deployment
metadata:
  name: webnodb
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: webnodb
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1    
  template:
    metadata:
      labels:
        app: webnodb
    spec:
      containers:
      - name: webnodb
        image: {{ .Values.image.webnodb }}
        ports:
        - containerPort: {{ .Values.ports.webnodb }}
        resources:
          requests: {{ .Values.resources.requests | toYaml | nindent 12 }}
          limits: {{ .Values.resources.limits | toYaml | nindent 12 }}
    
---
apiVersion: v1
kind: Service
metadata:
  name: webnodb-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: webnodb
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.ports.webnodb }}
  type: ClusterIP
