apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: mbissouri
spec:
  serviceName: mongodb
  replicas: 3
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0
        command:
        - "mongod"
        - "--replSet"
        - "rs0"
        - "--bind_ip"
        - "0.0.0.0"
        ports:
        - containerPort: 27017
        resources:
          requests:
            memory: "200Mi"
            cpu: "200m"
          limits:
            memory: "400Mi" 
            cpu: "400m"
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongodb-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi